- name: Install ruby and Bundler
  hosts: all
  become: true
  tasks:
  - name: Install ruby and update cache
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - ruby-full
      - ruby-bundler
      - build-essential
